name: 'AuthZ Domain Analyzer'
description: 'Process an authorization domain and produce documentation'
inputs:
  domain-file:  # id of input
    description: 'The authorization domain file to be processed'
    required: true
    default: './domain.yaml'
outputs:
  report: # id of output
    description: 'The content of the markdown file'
runs:
  using: 'node20'
  main: 'index.js'
