name: 'AuthZ Domain Analyzer'
description: 'Process an authorization domain and produce documentation'
inputs:
  domain-file:  # id of input
    description: 'The authorization domain file to be processed'
    required: true
    default: './domain.yaml'
  output-file:  # id of input
    description: 'The output md file'
    required: true
    default: './domain.md'
runs:
  using: 'node20'
  main: 'index.js'
